# Generated by Django 5.0.6 on 2024-07-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art2D',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageFileName', models.CharField(max_length=255)),
                ('MainCategory', models.CharField(max_length=255)),
                ('SubCategory', models.CharField(max_length=255)),
                ('MiddleCategory', models.CharField(max_length=255)),
                ('Class_kor', models.CharField(max_length=255)),
                ('ArtTitle_kor', models.CharField(max_length=255)),
                ('ArtistName_kor', models.CharField(max_length=255)),
                ('Image', models.BinaryField()),
            ],
            options={
                'db_table': 'art_2d',
            },
        ),
    ]
